from typing import Dict
from datetime import datetime
from .researcher import ResearchAgent
from .analyzer import AnalysisAgent
from .writer import WriterAgent
from .fact_checker import FactCheckerAgent
from utils.logger import AgentLogger


class CoordinatorAgent:
    
    def __init__(self, api_key: str, max_search_results: int = 5, temperature: float = 0.7):
        self.logger = AgentLogger()
        
        self.research_agent = ResearchAgent(api_key, max_search_results)
        self.analysis_agent = AnalysisAgent(api_key, temperature)
        self.writer_agent = WriterAgent(api_key, temperature)
        self.fact_checker = FactCheckerAgent(api_key, temperature)
    
    async def execute_research_pipeline(self, topic: str, depth: str = "standard") -> Dict:
        """
        Run the complete research pipeline
        
        Steps:
        1. Research Agent searches the web
        2. Analysis Agent extracts insights
        3. Writer Agent creates report
        4. Fact-Checker verifies quality
        """
        
        self.logger.log("Coordinator", f"Starting research on: {topic}")
        
        try:
            # Step 1: Research
            self.logger.log("Coordinator", "Step 1: Researching...")
            research_data = await self.research_agent.research(topic, depth)
            self.logger.log("Coordinator", "Research complete", "success")
            
            self.logger.log("Coordinator", "Step 2: Analyzing...")
            analysis = await self.analysis_agent.analyze(research_data, topic)
            self.logger.log("Coordinator", "Analysis complete", "success")
            
            self.logger.log("Coordinator", "Step 3: Writing report...")
            report = await self.writer_agent.write_report(topic, research_data, analysis)
            self.logger.log("Coordinator", "Report written", "success")
            
            self.logger.log("Coordinator", "Step 4: Fact-checking...")
            verification = await self.fact_checker.verify(report, topic)
            self.logger.log("Coordinator", "Fact-check complete", "success")
            
            final_report = self._create_final_report(topic, report, verification)
            
            self.logger.log("Coordinator", "All done! Report ready.", "success")
            
            return {
                'report': final_report,
                'logs': self.logger.get_logs(),
                'metadata': {
                    'topic': topic,
                    'depth': depth,
                    'timestamp': datetime.now().isoformat()
                }
            }
            
        except Exception as e:
            self.logger.log("Coordinator", f"Error: {str(e)}", "error")
            raise Exception(f"Pipeline failed: {str(e)}")
    
    def _create_final_report(self, topic: str, report: str, verification: str) -> str:        
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return f"""Research Report: {topic}

**Generated:** {timestamp}
---
{report}
---
## Quality Verification
{verification}
---
*Report generated by Multi-Agent Research System*
"""